# Generated by Django 5.0.7 on 2024-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Last updated date', verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated date', verbose_name='Last Updated Date')),
                ('status', models.CharField(default='active', help_text='is the  object active', max_length=20, verbose_name='is_active')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=200, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=255, verbose_name='Last Name')),
                ('auth_provider', models.CharField(blank=True, default='email', help_text='Authentication provider', max_length=255, verbose_name='Auth Provider')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user active?', verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, help_text='Is the user an admin?', verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, help_text='A staff', verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
