# Generated by Django 5.0.7 on 2024-07-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_data.plot'),
        ),
    ]
