# Generated by Django 5.0.7 on 2024-07-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_data', '0002_alter_elementdata_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaldata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_data.plot'),
        ),
        migrations.AlterField(
            model_name='plothardwaredata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_data.plot'),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_data.plot'),
        ),
    ]
