# Generated by Django 5.0.7 on 2024-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_data', '0003_alter_environmentaldata_plot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='current_crop_type',
            field=models.CharField(help_text='Current crop cultivated', max_length=250, verbose_name='Current Crop Type'),
        ),
    ]
